bug 798444 - check that PID is still running before keeping lock

diff --git a/scripts/crons/socorrorc b/scripts/crons/socorrorc
--- a/scripts/crons/socorrorc
+++ b/scripts/crons/socorrorc
@@ -22,8 +22,17 @@ function lock {
   JOB=$1
   if [ -f "/tmp/${JOB}.lock" ]
   then
-    echo "error (lock): lock already exists for ${JOB}"
-    exit 1
+    PID=`cat /tmp/${JOB}.lock`
+    ps -p $PID > /dev/null
+    if [ $? == 0 ]
+    then
+      echo "error (lock): lock already exists for ${JOB} pid ${PID}"
+      exit 1
+    else
+      echo "warn (lock): removing lock for ${JOB}, ${PID} not running"
+      unlock ${JOB}
+      return 1
+    fi
   fi
   echo $$ > /tmp/${JOB}.lock
 }
